---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
        - name: health-care
          image: bromaaascripts/health-care:v1.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: health-care
spec:
  type: NodePort
  selector:
    app: health-care
  ports:
    - port: 8081
      targetPort: 8081
