---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-container
        image: bromaaascripts/health-care:$BUILD_NUMBER
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
